### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by momozor** [momozor/python-pixabay#2]
The documentation need to be reformed with much more detailed informations and guides.

**Comment by faraco** [comment]
Better documentation has been made with Doxygen. The HTML is included in master branch and also online at https://faraco.github.io/python-pixabay/html/index.html.

This issue now can be closed.

**Comment by momozor** [comment]
Use reStructuredText (rst) format for documentation. Currently, I'm planning to put all the documentation code in the `pixabay.py` file.

**Comment by momozor** [comment]
* [ ] Use markdown for doc
