### ISSUE TITLE
Pixabay API parameter: page changed to pagi

### ISSUE THREAD

**Issue by meegoStar** [momozor/python-pixabay#5]
It seems that Pixabay API parameter `page` should be changed to `pagi` when sending GET. Otherwise, when the value of `page` getting larger, it would be easy to get `[ERROR 400] "page" is out of valid range.`

**Comment by momozor** [comment]
Hello! Thanks for reporting this issue!

I have a question. What do you actually mean by `pagi`? I cannot find such parameter from the official Pixabay API [documentation](https://pixabay.com/api/docs/) and I can't proceed to implement this feature to avoid breaking the API.

**Comment by meegoStar** [comment]
Yes, it seems weird since on Pixabay official API documentation, it is `page` instead of `pagi` for selecting the page number.

But I found that for instance in this sample scenario: searching "nature" images on Pixabay with page number = `5`,
1. https://pixabay.com/api/?key=[YOUR-KEY-HERE]&q=nature&lang=en&response_group=high_resolution&image_type=photo&orientation=horizontal&category=all&safesearch=true&order=latest&page=5&per_page=200 **(using `page`)**
2. http://pixabay.com/api/?key=[YOUR-KEY-HERE]&q=nature&lang=en&response_group=high_resolution&image_type=photo&orientation=horizontal&category=all&safesearch=true&order=latest&pagi=1&per_page=200 **(using `pagi`)**
3. https://pixabay.com/en/photos/nature/?pagi=5 **(Pixabay web page URL)**

in the first case, it would result in `[ERROR 400] "page" is out of valid range.`, while in the other 2 cases, I could get search results successfully, in JSON and web page forms respectively.

**Comment by momozor** [comment]
@meegoStar Yes. You are correct on that. `pagi` parameter does work on large integer values unlike `page`. 

I'm currently waiting for Pixabay support email reply to ask why `pagi` works properly with the API and why it is not even documented in the first place.

Good catch :)

**Comment by momozor** [comment]
@meegoStar 


> If you have properly implemented the API and you need more requests, we can increase the rate limit at any time. 5,000 requests per hour goes a long way, so please first check if you really come close to this limit before asking. Proper implementation particularly includes giving credits to Pixabay whenever search results are displayed and caching API responses for 24 hours. Also, the API may only be used to let real people search for images and videos. Automated requests should be avoided.

Their reply seems a little bit unclear, but I'm assuming `pagi` is for the *extra* option of the API, hence why it is not documented. It's weird that they let the parameter to be used publicly and without any docs if that is the case, though..

**Comment by meegoStar** [comment]
That's a little bit strange to me. Still take the scenario above for example, if a real person just want to jump at the fifth search result page with 200 images per page, even we take the previous four pages into account, there should be at most 5 requests containing 1000 result images right? If the number of requests per hour does not exceed the limit, I don't understand why we cannot retrieve the search results at the fifth page using `page`.

**Comment by momozor** [comment]
I think, I'll just add `pagi` parameter alongside `page` as an option.

**Comment by meegoStar** [comment]
Got it!

**Comment by momozor** [comment]
@meegoStar There is only one problem. `928382323828818891893891892893828382382838283283828382838238283823828382832832` works for pagi too. I doubt Pixabay has such amount of pages.

**Comment by meegoStar** [comment]
Based on my experience, I guess there would be plenty of duplicate images. It's really confusing.

**Comment by momozor** [comment]
Hmm. I've decided to only use the officially documented parameters. The biggest issue with parameters such as `pagi` is that they are undefined and we really don't know what they will do. It may cause further trouble too. I'm clossing this issue for now. Thanks for feedbacks.

**Comment by peardox** [comment]
I hate Google - it led me to this drivel

pagi-X is ignored and you get page=1 (the default)

**Comment by rahulsingh03** [comment]
@momozor have you come up with the solution regarding error 400. Cause I am not able to download pics more than 600 anyway. So it just defeat the purpose of using an API.
